project_id = "duindorp-tenueportaal-local"

[api]
port = 54329

[db]
port = 54339

[studio]
port = 54349

[local_smtp]
enabled = true
port = 54359

[analytics]
enabled = true
port = 54369
backend = "postgres"
