project_id = "duindorp-tenueportaal-local"

[api]
port = 54329
schemas = ["public", "graphql_public", "app"]
extra_search_path = ["public", "extensions"]

[db]
port = 54339

[studio]
port = 54349

[local_smtp]
enabled = true
port = 54359

[analytics]
enabled = true
port = 54369
backend = "postgres"

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
