import { createPublicKey, verify } from "node:crypto";
import { z } from "zod";
import type { SendGridOperationalEvent } from "../webhook";

const envelopeSchema = z.object({ Type: z.enum(["Notification", "SubscriptionConfirmation"]), MessageId: z.string().min(1).max(240), TopicArn: z.string().min(1).max(512), Message: z.string().max(1_000_000), Timestamp: z.string().datetime(), SignatureVersion: z.enum(["1", "2"]), Signature: z.string().min(1).max(2048), SigningCertURL: z.string().url().max(2048), Subject: z.string().max(1000).optional(), Token: z.string().max(2048).optional(), SubscribeURL: z.string().url().max(2048).optional() }).strict();
export type SnsEnvelope = z.infer<typeof envelopeSchema>;
export function parseSnsEnvelope(raw: string) { let value: unknown; try { value = JSON.parse(raw); } catch { throw new Error("SNS_BODY_INVALID"); } const parsed = envelopeSchema.safeParse(value); if (!parsed.success) throw new Error("SNS_BODY_INVALID"); return parsed.data; }
function snsUrl(value: string) { const url = new URL(value); if (url.protocol !== "https:" || url.username || url.password || (url.port && url.port !== "443") || !/^sns\.[a-z0-9-]+\.amazonaws\.com$/u.test(url.hostname)) throw new Error("SNS_URL_INVALID"); return url; }
export function validateSigningCertUrl(value: string) { const url = snsUrl(value); if (!/^\/SimpleNotificationService-[A-Za-z0-9_-]+\.pem$/u.test(url.pathname) || url.search || url.hash) throw new Error("SNS_CERT_URL_INVALID"); return url; }
function canonical(e: SnsEnvelope) { const fields = e.Type === "Notification" ? ["Message", "MessageId", ...(e.Subject ? ["Subject"] : []), "Timestamp", "TopicArn", "Type"] : ["Message", "MessageId", "SubscribeURL", "Timestamp", "Token", "TopicArn", "Type"]; return fields.map((key) => `${key}\n${String(e[key as keyof SnsEnvelope] ?? "")}\n`).join(""); }
export async function verifySnsEnvelope(e: SnsEnvelope, fetcher: typeof fetch = fetch) { if (e.TopicArn !== process.env.SES_SNS_TOPIC_ARN) return false; try { const certUrl = validateSigningCertUrl(e.SigningCertURL); const response = await fetcher(certUrl, { redirect: "error", signal: AbortSignal.timeout(3000) }); if (!response.ok || Number(response.headers.get("content-length") ?? 0) > 32_000) return false; const certificate = await response.text(); if (certificate.length > 32_000) return false; return verify(e.SignatureVersion === "1" ? "RSA-SHA1" : "RSA-SHA256", Buffer.from(canonical(e)), createPublicKey(certificate), Buffer.from(e.Signature, "base64")); } catch { return false; } }
const sesSchema = z.object({ eventType: z.enum(["SEND", "DELIVERY", "BOUNCE", "COMPLAINT", "REJECT", "DELIVERY_DELAY"]), mail: z.object({ messageId: z.string().min(1).max(240), timestamp: z.string().datetime(), tags: z.record(z.array(z.string().max(240)).max(2)).default({}) }).passthrough() }).passthrough();
function only(tags: Record<string,string[]>, key: string) { return tags[key]?.length === 1 ? tags[key][0] : undefined; }
export function parseSesOperationalEvent(e: SnsEnvelope): SendGridOperationalEvent | null { let value: unknown; try { value = JSON.parse(e.Message); } catch { throw new Error("SES_EVENT_INVALID"); } const p = sesSchema.safeParse(value); if (!p.success) throw new Error("SES_EVENT_INVALID"); const map = { DELIVERY: "delivered", BOUNCE: "bounced", COMPLAINT: "dropped", REJECT: "dropped", DELIVERY_DELAY: "deferred" } as const; if (p.data.eventType === "SEND") return null; const eventType = map[p.data.eventType]; const tags = p.data.mail.tags; const kind = only(tags,"delivery_kind"); const job = only(tags,"email_job_id"), attempt = only(tags,"delivery_attempt_id"), otp = only(tags,"otp_delivery_attempt_id"), test = only(tags,"test_delivery_id"); const uuid = z.string().uuid(); const identity = { providerEventId: e.MessageId, providerMessageId: p.data.mail.messageId, eventType, occurredAt: p.data.mail.timestamp };
 if (kind === "email_job" && uuid.safeParse(job).success && uuid.safeParse(attempt).success && !otp && !test) return { target:"email_job", emailJobId: job!, deliveryAttemptId: attempt!, ...identity };
 if (kind === "parent_otp" && uuid.safeParse(otp).success && !job && !attempt && !test) return { target:"parent_otp", deliveryAttemptId: otp!, ...identity };
 if (kind === "admin_test" && uuid.safeParse(test).success && !job && !attempt && !otp) return { target:"mail_test", testDeliveryId: test!, deliveryAttemptId: test!, ...identity };
 throw new Error("SES_EVENT_IDENTITY_INVALID"); }
export async function confirmSnsSubscription(e: SnsEnvelope, fetcher: typeof fetch = fetch) { if (e.Type !== "SubscriptionConfirmation" || process.env.SES_SNS_AUTO_CONFIRM !== "true" || !e.SubscribeURL || !e.Token) return false; const url = snsUrl(e.SubscribeURL); const response = await fetcher(url, { redirect:"error", signal: AbortSignal.timeout(3000) }); return response.ok; }
